"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pingstdagen = exports.WhitSunday = exports.Valborgsmaessoafton = exports.WalpurgisNight = exports.Trettondagsafton = exports.TwelfthNight = exports.Pingstafton = exports.PentecostEve = exports.Nyaarsafton = exports.NewYearsEve = exports.Nyaarsdagen = exports.NewYearsDay = exports.SverigesNationaldag = exports.NationalDay = exports.Midsommarafton = exports.MidsummerEve = exports.Midsommardagen = exports.MidsummerDay = exports.FoerstaMaj = exports.MayFirst = exports.Skaertorsdagen = exports.MaundyThursday = exports.Paaskafton = exports.HolySaturday = exports.Laangfredagen = exports.GoodFriday = exports.TrettondedagJul = exports.Epiphany = exports.Paaskdagen = exports.EasterSunday = exports.AnnandagPaask = exports.EasterMonday = exports.Julafton = exports.ChristmasEve = exports.Juldagen = exports.ChristmasDay = exports.AnnandagJul = exports.BoxingDay = exports.KristiHimmelsfaerdsdag = exports.AscensionDay = exports.Allhelgonaafton = exports.AllSaintsEve = exports.AllaHelgonsDag = exports.AllSaintsDay = void 0;
var all_saints_day_1 = require("./all-saints-day");
Object.defineProperty(exports, "AllSaintsDay", { enumerable: true, get: function () { return __importDefault(all_saints_day_1).default; } });
Object.defineProperty(exports, "AllaHelgonsDag", { enumerable: true, get: function () { return __importDefault(all_saints_day_1).default; } });
var all_saints_eve_1 = require("./all-saints-eve");
Object.defineProperty(exports, "AllSaintsEve", { enumerable: true, get: function () { return __importDefault(all_saints_eve_1).default; } });
Object.defineProperty(exports, "Allhelgonaafton", { enumerable: true, get: function () { return __importDefault(all_saints_eve_1).default; } });
var ascension_day_1 = require("./ascension-day");
Object.defineProperty(exports, "AscensionDay", { enumerable: true, get: function () { return __importDefault(ascension_day_1).default; } });
Object.defineProperty(exports, "KristiHimmelsfaerdsdag", { enumerable: true, get: function () { return __importDefault(ascension_day_1).default; } });
var boxing_day_1 = require("./boxing-day");
Object.defineProperty(exports, "BoxingDay", { enumerable: true, get: function () { return __importDefault(boxing_day_1).default; } });
Object.defineProperty(exports, "AnnandagJul", { enumerable: true, get: function () { return __importDefault(boxing_day_1).default; } });
var christmas_day_1 = require("./christmas-day");
Object.defineProperty(exports, "ChristmasDay", { enumerable: true, get: function () { return __importDefault(christmas_day_1).default; } });
Object.defineProperty(exports, "Juldagen", { enumerable: true, get: function () { return __importDefault(christmas_day_1).default; } });
var christmas_eve_1 = require("./christmas-eve");
Object.defineProperty(exports, "ChristmasEve", { enumerable: true, get: function () { return __importDefault(christmas_eve_1).default; } });
Object.defineProperty(exports, "Julafton", { enumerable: true, get: function () { return __importDefault(christmas_eve_1).default; } });
var easter_monday_1 = require("./easter-monday");
Object.defineProperty(exports, "EasterMonday", { enumerable: true, get: function () { return __importDefault(easter_monday_1).default; } });
Object.defineProperty(exports, "AnnandagPaask", { enumerable: true, get: function () { return __importDefault(easter_monday_1).default; } });
var easter_sunday_1 = require("./easter-sunday");
Object.defineProperty(exports, "EasterSunday", { enumerable: true, get: function () { return __importDefault(easter_sunday_1).default; } });
Object.defineProperty(exports, "Paaskdagen", { enumerable: true, get: function () { return __importDefault(easter_sunday_1).default; } });
var epiphany_1 = require("./epiphany");
Object.defineProperty(exports, "Epiphany", { enumerable: true, get: function () { return __importDefault(epiphany_1).default; } });
Object.defineProperty(exports, "TrettondedagJul", { enumerable: true, get: function () { return __importDefault(epiphany_1).default; } });
var good_friday_1 = require("./good-friday");
Object.defineProperty(exports, "GoodFriday", { enumerable: true, get: function () { return __importDefault(good_friday_1).default; } });
Object.defineProperty(exports, "Laangfredagen", { enumerable: true, get: function () { return __importDefault(good_friday_1).default; } });
var holy_saturday_1 = require("./holy-saturday");
Object.defineProperty(exports, "HolySaturday", { enumerable: true, get: function () { return __importDefault(holy_saturday_1).default; } });
Object.defineProperty(exports, "Paaskafton", { enumerable: true, get: function () { return __importDefault(holy_saturday_1).default; } });
var maundy_thursday_1 = require("./maundy-thursday");
Object.defineProperty(exports, "MaundyThursday", { enumerable: true, get: function () { return __importDefault(maundy_thursday_1).default; } });
Object.defineProperty(exports, "Skaertorsdagen", { enumerable: true, get: function () { return __importDefault(maundy_thursday_1).default; } });
var may_first_1 = require("./may-first");
Object.defineProperty(exports, "MayFirst", { enumerable: true, get: function () { return __importDefault(may_first_1).default; } });
Object.defineProperty(exports, "FoerstaMaj", { enumerable: true, get: function () { return __importDefault(may_first_1).default; } });
var midsummer_day_1 = require("./midsummer-day");
Object.defineProperty(exports, "MidsummerDay", { enumerable: true, get: function () { return __importDefault(midsummer_day_1).default; } });
Object.defineProperty(exports, "Midsommardagen", { enumerable: true, get: function () { return __importDefault(midsummer_day_1).default; } });
var midsummer_eve_1 = require("./midsummer-eve");
Object.defineProperty(exports, "MidsummerEve", { enumerable: true, get: function () { return __importDefault(midsummer_eve_1).default; } });
Object.defineProperty(exports, "Midsommarafton", { enumerable: true, get: function () { return __importDefault(midsummer_eve_1).default; } });
var national_day_1 = require("./national-day");
Object.defineProperty(exports, "NationalDay", { enumerable: true, get: function () { return __importDefault(national_day_1).default; } });
Object.defineProperty(exports, "SverigesNationaldag", { enumerable: true, get: function () { return __importDefault(national_day_1).default; } });
var new_years_day_1 = require("./new-years-day");
Object.defineProperty(exports, "NewYearsDay", { enumerable: true, get: function () { return __importDefault(new_years_day_1).default; } });
Object.defineProperty(exports, "Nyaarsdagen", { enumerable: true, get: function () { return __importDefault(new_years_day_1).default; } });
var new_years_eve_1 = require("./new-years-eve");
Object.defineProperty(exports, "NewYearsEve", { enumerable: true, get: function () { return __importDefault(new_years_eve_1).default; } });
Object.defineProperty(exports, "Nyaarsafton", { enumerable: true, get: function () { return __importDefault(new_years_eve_1).default; } });
var pentecost_eve_1 = require("./pentecost-eve");
Object.defineProperty(exports, "PentecostEve", { enumerable: true, get: function () { return __importDefault(pentecost_eve_1).default; } });
Object.defineProperty(exports, "Pingstafton", { enumerable: true, get: function () { return __importDefault(pentecost_eve_1).default; } });
var twelfth_night_1 = require("./twelfth-night");
Object.defineProperty(exports, "TwelfthNight", { enumerable: true, get: function () { return __importDefault(twelfth_night_1).default; } });
Object.defineProperty(exports, "Trettondagsafton", { enumerable: true, get: function () { return __importDefault(twelfth_night_1).default; } });
var walpurgis_night_1 = require("./walpurgis-night");
Object.defineProperty(exports, "WalpurgisNight", { enumerable: true, get: function () { return __importDefault(walpurgis_night_1).default; } });
Object.defineProperty(exports, "Valborgsmaessoafton", { enumerable: true, get: function () { return __importDefault(walpurgis_night_1).default; } });
var whit_sunday_1 = require("./whit-sunday");
Object.defineProperty(exports, "WhitSunday", { enumerable: true, get: function () { return __importDefault(whit_sunday_1).default; } });
Object.defineProperty(exports, "Pingstdagen", { enumerable: true, get: function () { return __importDefault(whit_sunday_1).default; } });
//# sourceMappingURL=index.js.map